### ISSUE TITLE
Publish ToFixed as an elm package

### ISSUE THREAD

**Issue by focusaurus** [IwalkAlone/elephant-guide#1]
Would you consider publishing the ToFixed.elm module in this repo as an elm package for community use?

**Comment by IwalkAlone** [comment]
I lifted it from a published package a while ago myself, but can't remember which one. http://package.elm-lang.org/packages/krisajenkins/formatting/ has this functionality, I'd suggest using that

**Comment by focusaurus** [comment]
Yeah I subsequently found myrho/elm-round which suffices as well.
